package com.wisdom.webservice.schedule.entity;

import com.wisdom.webservice.PropertiesLoaderUtils;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * WF_ApplicationToDoService  待办
 *
 * This class was generated by Apache CXF 3.2.10
 * 2019-08-31T09:45:36.647+08:00
 * Generated source version: 3.2.10
 *
 */
@WebServiceClient(name = "WF_ApplicationToDoService",
                  wsdlLocation = "",
                  targetNamespace = "http://www.szmetro.cn/")
public class WFApplicationToDoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.szmetro.cn/", "WF_ApplicationToDoService");
    public final static QName WFApplicationToDoServiceSoap12 = new QName("http://www.szmetro.cn/", "WF_ApplicationToDoServiceSoap12");
    public final static QName WFApplicationToDoServiceSoap = new QName("http://www.szmetro.cn/", "WF_ApplicationToDoServiceSoap");
    static {
        URL url = null;
        String urlStr = null;
        try {
            PropertiesLoaderUtils prop = new PropertiesLoaderUtils("webServiceConfig.yml");
            urlStr = prop.getProperty("webservice.daiban.url");
            url = new URL(urlStr);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WFApplicationToDoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", urlStr);
        }
        WSDL_LOCATION = url;
    }

    public WFApplicationToDoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WFApplicationToDoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WFApplicationToDoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WFApplicationToDoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WFApplicationToDoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WFApplicationToDoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WFApplicationToDoServiceSoap
     */
    @WebEndpoint(name = "WF_ApplicationToDoServiceSoap12")
    public WFApplicationToDoServiceSoap getWFApplicationToDoServiceSoap12() {
        return super.getPort(WFApplicationToDoServiceSoap12, WFApplicationToDoServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WFApplicationToDoServiceSoap
     */
    @WebEndpoint(name = "WF_ApplicationToDoServiceSoap12")
    public WFApplicationToDoServiceSoap getWFApplicationToDoServiceSoap12(WebServiceFeature... features) {
        return super.getPort(WFApplicationToDoServiceSoap12, WFApplicationToDoServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns WFApplicationToDoServiceSoap
     */
    @WebEndpoint(name = "WF_ApplicationToDoServiceSoap")
    public WFApplicationToDoServiceSoap getWFApplicationToDoServiceSoap() {
        return super.getPort(WFApplicationToDoServiceSoap, WFApplicationToDoServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WFApplicationToDoServiceSoap
     */
    @WebEndpoint(name = "WF_ApplicationToDoServiceSoap")
    public WFApplicationToDoServiceSoap getWFApplicationToDoServiceSoap(WebServiceFeature... features) {
        return super.getPort(WFApplicationToDoServiceSoap, WFApplicationToDoServiceSoap.class, features);
    }

}
