package com.wisdom.webservice.schedule.entity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-08-31T09:45:36.623+08:00
 * Generated source version: 3.2.10
 *
 */
@WebService(targetNamespace = "http://www.szmetro.cn/", name = "WF_ApplicationToDoServiceSoap")
@XmlSeeAlso({com.wisdom.webservice.token.ObjectFactory.class, ObjectFactory.class})
public interface WFApplicationToDoServiceSoap {

    /**
     * SaveOrUpdateWF_ApplicationInfo 保存待办信息
     */
    @WebMethod(operationName = "SaveWF_ApplicationInfo", action = "http://www.szmetro.cn/SaveWF_ApplicationInfo")
    @RequestWrapper(localName = "SaveWF_ApplicationInfo", targetNamespace = "http://www.szmetro.cn/", className = "com.wisdom.webservice.schedule.entity.SaveWFApplicationInfo")
    @ResponseWrapper(localName = "SaveWF_ApplicationInfoResponse", targetNamespace = "http://www.szmetro.cn/", className = "com.wisdom.webservice.schedule.entity.SaveWFApplicationInfoResponse")
    @WebResult(name = "SaveWF_ApplicationInfoResult", targetNamespace = "http://www.szmetro.cn/")
    public boolean saveWFApplicationInfo(
            @WebParam(name = "SystemID", targetNamespace = "http://www.szmetro.cn/") Integer systemID,
            @WebParam(name = "ProcName", targetNamespace = "http://www.szmetro.cn/") String procName,
            @WebParam(name = "ImpoLevel", targetNamespace = "http://www.szmetro.cn/") Integer impoLevel,
            @WebParam(name = "Alias", targetNamespace = "http://www.szmetro.cn/") String alias,
            @WebParam(name = "PasserName", targetNamespace = "http://www.szmetro.cn/") String passerName,
            @WebParam(name = "ReceTime", targetNamespace = "http://www.szmetro.cn/")
                    javax.xml.datatype.XMLGregorianCalendar receTime,
            @WebParam(name = "LoginID", targetNamespace = "http://www.szmetro.cn/") String loginID,
            @WebParam(name = "SystemURL", targetNamespace = "http://www.szmetro.cn/") String systemURL,
            @WebParam(name = "ProcID", targetNamespace = "http://www.szmetro.cn/") String procID,
            @WebParam(name = "TaskID", targetNamespace = "http://www.szmetro.cn/") Integer taskID,
            @WebParam(name = "AppName", targetNamespace = "http://www.szmetro.cn/") String appName,
            @WebParam(name = "CreatorName", targetNamespace = "http://www.szmetro.cn/") String creatorName);

    /**
     * DeleteWF_ApplicationInfo 删除待办信息
     */
    @WebMethod(operationName = "DeleteWF_ApplicationInfo", action = "http://www.szmetro.cn/DeleteWF_ApplicationInfo")
    @RequestWrapper(localName = "DeleteWF_ApplicationInfo", targetNamespace = "http://www.szmetro.cn/", className = "com.wisdom.webservice.schedule.entity.DeleteWFApplicationInfo")
    @ResponseWrapper(localName = "DeleteWF_ApplicationInfoResponse", targetNamespace = "http://www.szmetro.cn/", className = "com.wisdom.webservice.schedule.entity.DeleteWFApplicationInfoResponse")
    @WebResult(name = "DeleteWF_ApplicationInfoResult", targetNamespace = "http://www.szmetro.cn/")
    public boolean deleteWFApplicationInfo(
            @WebParam(name = "SystemID", targetNamespace = "http://www.szmetro.cn/") Integer systemID,
            @WebParam(name = "ProcID", targetNamespace = "http://www.szmetro.cn/") String procID);

    /**
     * DeleteWF_ApplicationInfoByTaskID 删除流程中某一步
     */
    @WebMethod(operationName = "DeleteWF_ApplicationInfoByTaskID", action = "http://www.szmetro.cn/DeleteWF_ApplicationInfoByTaskID")
    @RequestWrapper(localName = "DeleteWF_ApplicationInfoByTaskID", targetNamespace = "http://www.szmetro.cn/", className = "com.wisdom.webservice.schedule.entity.DeleteWFApplicationInfoByTaskID")
    @ResponseWrapper(localName = "DeleteWF_ApplicationInfoByTaskIDResponse", targetNamespace = "http://www.szmetro.cn/", className = "com.wisdom.webservice.schedule.entity.DeleteWFApplicationInfoByTaskIDResponse")
    @WebResult(name = "DeleteWF_ApplicationInfoByTaskIDResult", targetNamespace = "http://www.szmetro.cn/")
    public boolean deleteWFApplicationInfoByTaskID(
            @WebParam(name = "SystemID", targetNamespace = "http://www.szmetro.cn/") Integer systemID,
            @WebParam(name = "ProcID", targetNamespace = "http://www.szmetro.cn/") String procID,
            @WebParam(name = "TaskID", targetNamespace = "http://www.szmetro.cn/") Integer taskID);
}
