spring:
  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:www.nsst.cc}:${MYSQL_PORT:32273}/${MYSQL_DATABASE:xe}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 134WErte%&2
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis:
  basepackage: com.wisdom.acm.szxm.mapper
  xmlLocation: classpath:mapper/**/*.xml
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: "classpath*:mapper/**/*.xml"
  configuration:
    jdbc-type-for-null: varchar
