package com.wisdom.webservice.waiyantoken.entity;

import com.wisdom.webservice.PropertiesLoaderUtils;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-11-11T14:14:38.764+08:00
 * Generated source version: 3.2.10
 *
 */
@WebServiceClient(name = "GCToken",
                  wsdlLocation = "",
                  targetNamespace = "http://tempuri.org/")
public class GCToken extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "GCToken");
    public final static QName GCTokenSoap12 = new QName("http://tempuri.org/", "GCTokenSoap12");
    public final static QName GCTokenSoap = new QName("http://tempuri.org/", "GCTokenSoap");
    static {
        URL url = null;
        String urlStr = null;
        try {
            PropertiesLoaderUtils prop = new PropertiesLoaderUtils("webServiceConfig.yml");
            urlStr = prop.getProperty("webservice.hetongwaiyantoken.url");
            url = new URL(urlStr);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GCToken.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", urlStr);
        }
        WSDL_LOCATION = url;
    }

    public GCToken(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GCToken(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GCToken() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GCToken(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GCToken(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GCToken(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GCTokenSoap
     */
    @WebEndpoint(name = "GCTokenSoap12")
    public GCTokenSoap getGCTokenSoap12() {
        return super.getPort(GCTokenSoap12, GCTokenSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GCTokenSoap
     */
    @WebEndpoint(name = "GCTokenSoap12")
    public GCTokenSoap getGCTokenSoap12(WebServiceFeature... features) {
        return super.getPort(GCTokenSoap12, GCTokenSoap.class, features);
    }


    /**
     *
     * @return
     *     returns GCTokenSoap
     */
    @WebEndpoint(name = "GCTokenSoap")
    public GCTokenSoap getGCTokenSoap() {
        return super.getPort(GCTokenSoap, GCTokenSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GCTokenSoap
     */
    @WebEndpoint(name = "GCTokenSoap")
    public GCTokenSoap getGCTokenSoap(WebServiceFeature... features) {
        return super.getPort(GCTokenSoap, GCTokenSoap.class, features);
    }

}
