package com.wisdom.webservice.waiyantoken.entity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-11-11T14:14:38.744+08:00
 * Generated source version: 3.2.10
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "GCTokenSoap")
@XmlSeeAlso({com.wisdom.webservice.token.ObjectFactory.class, ObjectFactory.class})
public interface GCTokenSoap {

    @WebMethod(action = "http://tempuri.org/get")
    @RequestWrapper(localName = "get", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetResponse")
    @WebResult(name = "getResult", targetNamespace = "http://tempuri.org/")
    public String get(
            @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
                    String key
    );
}
