spring:
  datasource:
    name: test
    url: jdbc:oracle:thin:@//${ORACLE_HOST:127.0.0.1}:${ORACLE_PORT:1521}/ORCL #?useUnicode=true&characterEncoding=UTF8
    jdbc-url: jdbc:oracle:thin:@//${ORACLE_HOST:127.0.0.1}:${ORACLE_PORT:1521}/ORCL #?useUnicode=true&characterEncoding=UTF8
    username: acm_cloud_test
    password: acm_cloud_test
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  basepackage: com.wisdom.acm.activiti.mapper
  mapper-locations: classpath*:mapper/**/Oracle/*MapperOracle.xml,classpath*:mapper/**/*Mapper.xml
  configuration:
    jdbc-type-for-null: varchar


