spring:
  datasource:
    name: test
    url: jdbc:oracle:thin:@//${ORACLE_HOST:192.168.3.100}:${ORACLE_PORT:1521}/orcl #?useUnicode=true&characterEncoding=UTF8
    username: acm_cp
    password: acm_cp
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  basepackage: com.wisdom.acm.sys.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"
  configuration:
    jdbc-type-for-null: varchar


