logging:
    config: classpath:logback-spring.xml

spring:
    application:
        name: acm-center

server:
    port: 8761 #启动端口

eureka:
    server:
        enable-self-preservation: false  # 设为false，关闭自我保护
        eviction-interval-timer-in-ms: 3000  # 清理间隔（单位毫秒，默认是60*1000）启用主动失效，并且每次主动失效检测间隔为3s
        #use-read-only-response-cache: false #禁用Eureka的ReadOnlyMap缓存
        response-cache-update-interval-ms: 3000  #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
