logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: acm-module-hbase
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      indent-output: true
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  profiles:
    active: localhost,alimysql,tmm
  encrypt:
    key: wisdom!QAZ!@#123
    enabled: false
  main:
    allow-bean-definition-overriding: true

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: false

mybatis:
  basepackage: com.wisdom.acm.hbase.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

server:
  port: 8789


# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000


# 配置swagger
swagger:
  enabled: true
  base-package: com.wisdom.acm.hbase
  title: acm-module-hbase
  version: 1.0.0.SNAPSHOT
  description: 管理后端服务
  contact:
    name: admin

auth:
  serviceId: acm-auth-server
  user:
    token-header: Authorization
  client:
    id: acm-module-hbase
    secret: 123456
    token-header: x-client-token

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

license:
  subject: acm-license
  publicAlias: publicCert
  storePass: public_acm_@#123
  licensePath: license/license.lic
  publicKeysStorePath: license/publicCerts.keystore


# phoenix 数据源自定义配置
phoenix:
  enable: true
  url: jdbc:phoenix:127.0.0.1:2181:hbase
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
  username:
  password:
  default-auto-commit: true
  schema:
    isNamespaceMappingEnabled: true

