package com.wisdom.webservice.outstaff.entity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-08-31T09:44:51.484+08:00
 * Generated source version: 3.2.10
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "UUVPortalUserServicesSoap")
@XmlSeeAlso({com.wisdom.webservice.token.ObjectFactory.class, ObjectFactory.class})
public interface UUVPortalUserServicesSoap {

    @WebMethod(operationName = "ModifyPassword", action = "http://tempuri.org/ModifyPassword")
    @RequestWrapper(localName = "ModifyPassword", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.outstaff.entity.ModifyPassword")
    @ResponseWrapper(localName = "ModifyPasswordResponse", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.outstaff.entity.ModifyPasswordResponse")
    @WebResult(name = "ModifyPasswordResult", targetNamespace = "http://tempuri.org/")
    public boolean modifyPassword(
            @WebParam(name = "AccountName", targetNamespace = "http://tempuri.org/") String accountName,
            @WebParam(name = "NewPassword", targetNamespace = "http://tempuri.org/") String newPassword);

    /**
     * 创建UUV外部用户
     */
    @WebMethod(operationName = "CreateUUVPortalUser", action = "http://tempuri.org/CreateUUVPortalUser")
    @RequestWrapper(localName = "CreateUUVPortalUser", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.outstaff.entity.CreateUUVPortalUser")
    @ResponseWrapper(localName = "CreateUUVPortalUserResponse", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.outstaff.entity.CreateUUVPortalUserResponse")
    @WebResult(name = "CreateUUVPortalUserResult", targetNamespace = "http://tempuri.org/")
    public boolean createUUVPortalUser(
            @WebParam(name = "userId", targetNamespace = "http://tempuri.org/") String userId,
            @WebParam(name = "orgId", targetNamespace = "http://tempuri.org/") String orgId,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/") String userName,
            @WebParam(name = "loginId", targetNamespace = "http://tempuri.org/") String loginId,
            @WebParam(name = "sex", targetNamespace = "http://tempuri.org/") String sex,
            @WebParam(name = "mobilePhone", targetNamespace = "http://tempuri.org/") String mobilePhone,
            @WebParam(name = "email", targetNamespace = "http://tempuri.org/") String email,
            @WebParam(name = "idCard", targetNamespace = "http://tempuri.org/") String idCard);

    /**
     * 获取UUV外部用户
     */
    @WebMethod(operationName = "GetUUVPortalUserList", action = "http://tempuri.org/GetUUVPortalUserList")
    @RequestWrapper(localName = "GetUUVPortalUserList", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.outstaff.entity.GetUUVPortalUserList")
    @ResponseWrapper(localName = "GetUUVPortalUserListResponse", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.outstaff.entity.GetUUVPortalUserListResponse")
    @WebResult(name = "GetUUVPortalUserListResult", targetNamespace = "http://tempuri.org/")
    public com.wisdom.webservice.outstaff.entity.ArrayOfUserInfo getUUVPortalUserList(
            @WebParam(name = "appId", targetNamespace = "http://tempuri.org/") String appId,
            @WebParam(name = "IsContainPartTimeJob", targetNamespace = "http://tempuri.org/")
                    boolean isContainPartTimeJob,
            @WebParam(name = "beginLastUpdateDate", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar beginLastUpdateDate,
            @WebParam(name = "endLastUpdateDate", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar endLastUpdateDate);
}
