eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${DEPLOY_HOST:192.168.2.12}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:192.168.2.12}:${EUREKA_PORT:8761}/eureka/
