package com.wisdom.webservice.contract.entity;

import com.wisdom.webservice.PropertiesLoaderUtils;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-08-28T19:13:07.824+08:00
 * Generated source version: 3.2.10
 *
 */
@WebServiceClient(name = "GCService",
                  wsdlLocation = "",
                  targetNamespace = "http://tempuri.org/")
public class GCService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "GCService");
    public final static QName GCServiceSoap12 = new QName("http://tempuri.org/", "GCServiceSoap12");
    public final static QName GCServiceSoap = new QName("http://tempuri.org/", "GCServiceSoap");
    static {
        URL url = null;
        String urlStr = null;
        try {
            PropertiesLoaderUtils prop = new PropertiesLoaderUtils("webServiceConfig.yml");
            urlStr = prop.getProperty("webservice.contract.url");
            url = new URL(urlStr);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GCService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", urlStr);
        }
        WSDL_LOCATION = url;
    }

    public GCService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GCService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GCService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GCService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GCService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GCServiceSoap
     */
    @WebEndpoint(name = "GCServiceSoap12")
    public GCServiceSoap getGCServiceSoap12() {
        return super.getPort(GCServiceSoap12, GCServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GCServiceSoap
     */
    @WebEndpoint(name = "GCServiceSoap12")
    public GCServiceSoap getGCServiceSoap12(WebServiceFeature... features) {
        return super.getPort(GCServiceSoap12, GCServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns GCServiceSoap
     */
    @WebEndpoint(name = "GCServiceSoap")
    public GCServiceSoap getGCServiceSoap() {
        return super.getPort(GCServiceSoap, GCServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GCServiceSoap
     */
    @WebEndpoint(name = "GCServiceSoap")
    public GCServiceSoap getGCServiceSoap(WebServiceFeature... features) {
        return super.getPort(GCServiceSoap, GCServiceSoap.class, features);
    }

}
