logging:
  config: classpath:logback-spring.xml
sys:
  log:
    enable: 0

spring:
  application:
    name: acm-module-szxm
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      indent-output: true
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  profiles:
    active: localhost,alimysql
  encrypt:
    key: wisdom!QAZ!@#123
    enabled: false
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
      enabled: true
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            #quartz scheduler实例名
            instanceName: clusteredScheduler
            #定义每个scheduler节点的ID，使用AUTO保证在集群环境中保证ID的唯一性
            instanceId: AUTO
            #定义是否自动运行scheduler, 设置为true则应用启动时将自动启动quartz，为false则不启动。默认为true.
            autoStartup: true
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            //driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
    #初始化表结构
    #jdbc:
    #initialize-schema: never

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: false

server:
  port: 9874


# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000


# 配置swagger
swagger:
  enabled: true
  base-package: com.wisdom.acm.szxm
  title: acm-module-szxm
  version: 1.0.0.SNAPSHOT
  description: 管理后端服务
  contact:
    name: admin

auth:
  serviceId: acm-auth-server
  user:
    token-header: Authorization
  client:
    id: acm-module-szxm
    secret: 123456
    token-header: x-client-token

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

#中控考勤服务地址 相关
zkservice.url:
zkservice.key:
#企业微信 相关
ewx.serviceUrl: https://qyapi.weixin.qq.com/cgi-bin
ewx.corpId: ww7a7ca3d563092db6
ewx.agentId: 1000025
ewx.secretKey: giiuweI_JPIa37I81M44JzJ0KVKIxKFpKJI8OXrZF8U
ewx.kqSecretKey: MLOIij3dVQlYwBSi9lkH5iVLDDXsC_jziaC1eoWNyaM

#东软 相关
#正式环境 http://58.211.252.83:8104/co/oapi
neru.serviceUrl: http://58.211.252.83:8091/co/oapi
#neru.serviceUrl: http://58.211.252.83:8104/co/oapi
#正式环境 65198b5292d64ea69a952908c679f9d0
neru.appId: 68ce69533ae8490cacf95e1c1fb3d2cb
#neru.appId: 65198b5292d64ea69a952908c679f9d0
#正式环境 b9f49741-c358-4aa0-8bcf-3d2a783046b3
neru.secretKey: f9e9b44a-a7b3-449a-8b9d-1dfa2429ca34
#neru.secretKey: b9f49741-c358-4aa0-8bcf-3d2a783046b3
#正式环境 http://58.211.252.83:8104/snap-app-im/oapi/message/sendworkmsg
neru.sendmsgWorkUrl: http://58.211.252.83:8091/snap-app-im/oapi/message/sendworkmsg
#neru.sendmsgWorkUrl: http://58.211.252.83:8104/snap-app-im/oapi/message/sendworkmsg

sn: ##ACM对外单点登录地址
  ##ACM单点登录前端页面,需传入token
  acmSoLoginUrl: http://10.10.11.146:13000/static/index.html
  ##ACM登录页面
  acmLoginUrl: http://10.10.11.146:13000/login
systemIP: http://10.10.11.146:9874/sologin

#安全信息化平台 相关
#正式环境  暂无
security.serviceUrl: http://61.155.204.87:8888/SuZhouMonitor/login.do?method=checkLoginOpen
security.appKey: szdt-monitor-0001
security.secret: 0e14df212d20edd98d4bf204a435d0e8
