spring:
  datasource:
    name: test
    url: jdbc:oracle:thin:@//${ORACLE_HOST:192.168.2.179}:${ORACLE_PORT:1521}/xe #?useUnicode=true&characterEncoding=UTF8
    username: ${USER_NAME:acm_cloud_test}
    password: ${PASSWD:acm_cloud_test}
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver


mybatis:
  basepackage: com.wisdom.acm.sys.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"


