spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port:  ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    # docker 部署开启
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      #defaultZone: http://127.0.0.1:8761/eureka/
      # docker 部署开启
      defaultZone: http://${EUREKA_HOST:127.0.0.1}:${EUREKA_PORT:8761}/eureka/

#redis-cache 相关
redis:
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:1!TdNh0pXjitc5gf}
  timeout: 2000
  # 服务或应用名
  sysName: acm-module-wf
  enable: true
  database: 0
  expire: 720 #分钟

