package com.wisdom.webservice.outorg.entity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-08-31T09:43:06.518+08:00
 * Generated source version: 3.2.10
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "UUVPortalOrgServicesSoap")
@XmlSeeAlso({com.wisdom.webservice.token.ObjectFactory.class, ObjectFactory.class})
public interface UUVPortalOrgServicesSoap {

    /**
     * 创建UUV外部组织
     */
    @WebMethod(operationName = "CreateUUVPortalOrg", action = "http://tempuri.org/CreateUUVPortalOrg")
    @RequestWrapper(localName = "CreateUUVPortalOrg", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.outorg.entity.CreateUUVPortalOrg")
    @ResponseWrapper(localName = "CreateUUVPortalOrgResponse", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.outorg.entity.CreateUUVPortalOrgResponse")
    @WebResult(name = "CreateUUVPortalOrgResult", targetNamespace = "http://tempuri.org/")
    public boolean createUUVPortalOrg(@WebParam(name = "orgId", targetNamespace = "http://tempuri.org/") String orgId,
            @WebParam(name = "orgName", targetNamespace = "http://tempuri.org/") String orgName,
            @WebParam(name = "appId", targetNamespace = "http://tempuri.org/") String appId);

    /**
     * 获取UUV外部组织
     */
    @WebMethod(operationName = "GetUUVPortalOrgList", action = "http://tempuri.org/GetUUVPortalOrgList")
    @RequestWrapper(localName = "GetUUVPortalOrgList", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.outorg.entity.GetUUVPortalOrgList")
    @ResponseWrapper(localName = "GetUUVPortalOrgListResponse", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.outorg.entity.GetUUVPortalOrgListResponse")
    @WebResult(name = "GetUUVPortalOrgListResult", targetNamespace = "http://tempuri.org/")
    public com.wisdom.webservice.outorg.entity.ArrayOfADDepartmentInfo getUUVPortalOrgList(
            @WebParam(name = "appId", targetNamespace = "http://tempuri.org/") String appId,
            @WebParam(name = "beginLastUpdateDate", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar beginLastUpdateDate,
            @WebParam(name = "endLastUpdateDate", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar endLastUpdateDate);
}
