package com.wisdom.webservice.outorg.entity;

import com.wisdom.webservice.PropertiesLoaderUtils;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * UUV外部组织服务
 *
 * This class was generated by Apache CXF 3.2.10
 * 2019-08-31T09:43:06.543+08:00
 * Generated source version: 3.2.10
 *
 */
@WebServiceClient(name = "UUVPortalOrgServices",
                  wsdlLocation = "",
                  targetNamespace = "http://tempuri.org/")
public class UUVPortalOrgServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "UUVPortalOrgServices");
    public final static QName UUVPortalOrgServicesSoap12 = new QName("http://tempuri.org/", "UUVPortalOrgServicesSoap12");
    public final static QName UUVPortalOrgServicesSoap = new QName("http://tempuri.org/", "UUVPortalOrgServicesSoap");
    static {
        URL url = null;
        String urlStr = null;
        try {
            PropertiesLoaderUtils prop = new PropertiesLoaderUtils("webServiceConfig.yml");
            urlStr = prop.getProperty("webservice.outorg.url");
            url = new URL(urlStr);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UUVPortalOrgServices.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", urlStr);
        }
        WSDL_LOCATION = url;
    }

    public UUVPortalOrgServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UUVPortalOrgServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UUVPortalOrgServices() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UUVPortalOrgServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UUVPortalOrgServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UUVPortalOrgServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UUVPortalOrgServicesSoap
     */
    @WebEndpoint(name = "UUVPortalOrgServicesSoap12")
    public UUVPortalOrgServicesSoap getUUVPortalOrgServicesSoap12() {
        return super.getPort(UUVPortalOrgServicesSoap12, UUVPortalOrgServicesSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UUVPortalOrgServicesSoap
     */
    @WebEndpoint(name = "UUVPortalOrgServicesSoap12")
    public UUVPortalOrgServicesSoap getUUVPortalOrgServicesSoap12(WebServiceFeature... features) {
        return super.getPort(UUVPortalOrgServicesSoap12, UUVPortalOrgServicesSoap.class, features);
    }


    /**
     *
     * @return
     *     returns UUVPortalOrgServicesSoap
     */
    @WebEndpoint(name = "UUVPortalOrgServicesSoap")
    public UUVPortalOrgServicesSoap getUUVPortalOrgServicesSoap() {
        return super.getPort(UUVPortalOrgServicesSoap, UUVPortalOrgServicesSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UUVPortalOrgServicesSoap
     */
    @WebEndpoint(name = "UUVPortalOrgServicesSoap")
    public UUVPortalOrgServicesSoap getUUVPortalOrgServicesSoap(WebServiceFeature... features) {
        return super.getPort(UUVPortalOrgServicesSoap, UUVPortalOrgServicesSoap.class, features);
    }

}
