logging:
  config: classpath:logback-spring.xml

sys:
  log:
    #日志（1：开启  0：关闭）
    enable: 0
  tmm:
    #三员管理开启（1：开启  0：关闭）
    enable: 0
  menu:
    list:
      #下拉菜单（三级菜单）（1：开启  0：关闭）
      enable: 1

spring:
  application:
    name: acm-module-sys
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      indent-output: true
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  profiles:
    active: localhost,alimysql,tmm
  encrypt:
    key: wisdom!QAZ!@#123
    enabled: false
  main:
    allow-bean-definition-overriding: true

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: false

mybatis:
  basepackage: com.wisdom.acm.sys.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/**/*.xml"

server:
  port: 8762


# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000


# 配置swagger
swagger:
  enabled: true
  base-package: com.wisdom.acm.sys
  title: acm-module-sys
  version: 1.0.0.SNAPSHOT
  description: 管理后端服务
  contact:
    name: admin

auth:
  serviceId: acm-auth-server
  user:
    token-header: Authorization
  client:
    id: acm-module-sys
    secret: 123456
    token-header: x-client-token

management:
  endpoints:
    web:
      exposure:
        include: '*'

license:
  subject: ACM-LICENSE
  publicAlias: publicCert
  storePass: public_acm_@#123
  licensePath: license/license.lic
  publicKeysStorePath: license/publicCerts.keystore

uuv:
  task:
    # 定时同步任务每天中午12点半执行  0 30 12 * * ?
    corn: 0 30 12 * * ?
    # 定时同步任务每天晚上22点执行  0 0 22 * * ?
    #corn: 0 0 22 * * ?

#外延接入合同的登录接口 参数加密公钥
webservice.hetongwaiyantoken.publickey: phBFwcKZKtzH+gZJnjo57/qcMjWFtCIarXRE3p6+p66oHDBDR9sd5OwcygWolrifT/WOq298rzBrKZeuIulXVSSXKCtHRbCgOhkHra3LVJP0WVPHJYo0sX6r0EZ+wMGo/OWCwCcz0apa2irUTNKjHpsQWqsQx8o9ttNFI5Ttzfk=

#哈尔滨集成服务环境单点登录
sso:
  appId: sfb007773CEBA9A8D6B
  appSecret: ab753603c0bf4feaba20eb7941c47ab2
  #oauthUrl: http://221.226.30.122:8793/sso
  oauthUrl: http://172.16.2.34:10080/sso
  #uiasUrl: http://221.226.30.122:8794/uias
  uiasUrl: http://172.16.2.34:10081/uias
  portalUrl: http://172.16.2.33:8400/
  ssoLoginUrl: http://172.16.2.33:8400/static/index.html

##OA系统单点登录
oa:
  ##ACM单点登录前端页面,需传入token
  ssoLoginUrl: http://172.16.2.33:8400/static/index.html
  ##ACM登录页面
  loginUrl: http://172.16.2.33:8400/login