spring:
  redis:
    database: 2
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    pool:
    max-active: 20
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port:  ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    # docker 部署开启
    ip-address: 127.0.0.1
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    serviceUrl:
      #            defaultZone: http://221.226.30.122:8761/eureka/
      # docker 部署开启
      defaultZone: http://${EUREKA_HOST:127.0.0.1}:${EUREKA_PORT:8761}/eureka/
