logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: acm-module-base
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    default-property-inclusion: non_null
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  profiles:
    active: localhost,alimysql
  encrypt:
    key: wisdom!QAZ!@#123
    enabled: false
  main:
    allow-bean-definition-overriding: true

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: false

mybatis:
  basepackage: com.wisdom.acm.base.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/**/*.xml"

server:
  port: 8780


# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000


# 配置swagger
swagger:
  enabled: true
  base-package: com.wisdom.acm.base
  title: acm-module-base
  version: 1.0.0.SNAPSHOT
  description: 管理后端服务
  contact:
    name: admin

auth:
  serviceId: acm-auth-server
  user:
    token-header: Authorization
  client:
    id: acm-module-base
    secret: 123456
    token-header: x-client-token

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

license:
  subject: ACM-LICENSE
  publicAlias: publicCert
  storePass: public_acm_@#123
  licensePath: license/license.lic
  publicKeysStorePath: license/publicCerts.keystore

sys:
  log:
    #日志（1：开启  0：关闭）
    enable: 0


