package com.wisdom.webservice.internalstaff.entity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-08-31T09:42:25.257+08:00
 * Generated source version: 3.2.10
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "UUVGetSoap")
@XmlSeeAlso({com.wisdom.webservice.token.ObjectFactory.class, ObjectFactory.class})
public interface UUVGetSoap {

    @WebMethod(operationName = "GetUserList", action = "http://tempuri.org/GetUserList")
    @RequestWrapper(localName = "GetUserList", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.internalstaff.entity.GetUserList")
    @ResponseWrapper(localName = "GetUserListResponse", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.internalstaff.entity.GetUserListResponse")
    @WebResult(name = "GetUserListResult", targetNamespace = "http://tempuri.org/")
    public com.wisdom.webservice.internalstaff.entity.ArrayOfADUser getUserList(
            @WebParam(name = "IsContainPartTimeJob", targetNamespace = "http://tempuri.org/")
                    boolean isContainPartTimeJob);

    @WebMethod(operationName = "GetDepartMentList", action = "http://tempuri.org/GetDepartMentList")
    @RequestWrapper(localName = "GetDepartMentList", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.internalstaff.entity.GetDepartMentList")
    @ResponseWrapper(localName = "GetDepartMentListResponse", targetNamespace = "http://tempuri.org/", className = "com.wisdom.webservice.internalstaff.entity.GetDepartMentListResponse")
    @WebResult(name = "GetDepartMentListResult", targetNamespace = "http://tempuri.org/")
    public com.wisdom.webservice.internalstaff.entity.ArrayOfADDepartment getDepartMentList();
}
