package com.wisdom.webservice.internalstaff.entity;

import com.wisdom.webservice.PropertiesLoaderUtils;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.10
 * 2019-08-31T09:42:25.280+08:00
 * Generated source version: 3.2.10
 *
 */
@WebServiceClient(name = "UUVGet",
                  wsdlLocation = "",
                  targetNamespace = "http://tempuri.org/")
public class UUVGet extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "UUVGet");
    public final static QName UUVGetSoap = new QName("http://tempuri.org/", "UUVGetSoap");
    public final static QName UUVGetSoap12 = new QName("http://tempuri.org/", "UUVGetSoap12");
    static {
        URL url = null;
        String urlStr = null;
        try {
            PropertiesLoaderUtils prop = new PropertiesLoaderUtils("webServiceConfig.yml");
            urlStr = prop.getProperty("webservice.uuvinner.url");
            url = new URL(urlStr);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UUVGet.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", urlStr);
        }
        WSDL_LOCATION = url;
    }

    public UUVGet(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UUVGet(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UUVGet() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UUVGet(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UUVGet(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UUVGet(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UUVGetSoap
     */
    @WebEndpoint(name = "UUVGetSoap")
    public UUVGetSoap getUUVGetSoap() {
        return super.getPort(UUVGetSoap, UUVGetSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UUVGetSoap
     */
    @WebEndpoint(name = "UUVGetSoap")
    public UUVGetSoap getUUVGetSoap(WebServiceFeature... features) {
        return super.getPort(UUVGetSoap, UUVGetSoap.class, features);
    }


    /**
     *
     * @return
     *     returns UUVGetSoap
     */
    @WebEndpoint(name = "UUVGetSoap12")
    public UUVGetSoap getUUVGetSoap12() {
        return super.getPort(UUVGetSoap12, UUVGetSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UUVGetSoap
     */
    @WebEndpoint(name = "UUVGetSoap12")
    public UUVGetSoap getUUVGetSoap12(WebServiceFeature... features) {
        return super.getPort(UUVGetSoap12, UUVGetSoap.class, features);
    }

}
