eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    home-page-url-path: /
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    # docker 部署开启
  #        prefer-ip-address: true
  #        ip-address: ${DEPLOY_HOST:221.226.30.122}
    #服务刷新时间配置，每隔这个时间会主动心跳一次，默认30s
    lease-renewal-interval-in-seconds: 2
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除，默认90s
    lease-expiration-duration-in-seconds: 6
  client:
    serviceUrl:
      #            defaultZone: http://127.0.0.1:8761/eureka/
      # docker 部署开启
      defaultZone: http://${EUREKA_HOST:192.168.2.68}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    #eureka client刷新本地缓存时间，默认30s
    registry-fetch-interval-seconds: 4

spring:
  redis:
    database: 2
    host: ${REDIS_HOST:192.168.2.68}
    jedis:
      pool:
        max-active: 20
  rabbitmq:
    host: ${RABBIT_MQ_HOST:192.168.2.68}
    port:  ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest
